global:
  resolve_timeout: 1m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'teams'

receivers:
- name: 'teams'
  msteamsv2_configs:
    - send_resolved: true
      webhook_url: ''
      # Use your templates
      title: '{{ template "teams.title" . }}'
      text: '{{ template "teams.text" . }}'

templates:
  - '/etc/alertmanager/template.tmpl'