{
 "title": "Basic System Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "nodename",
    "label": "Server",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   },
   { "name": "job", "label": "Job", "query": { "query": "label_values(up,job)" } }
  ]
 },
 "panels": [
  {
   "title": "CPU Busy",
   "type": "stat",
   "description": "Overall CPU busy percentage (averaged across all cores)",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$nodename\"}[2m])))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "stat",
   "description": "Real RAM usage excluding cache and reclaimable memory",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$nodename\"} - node_memory_MemAvailable_bytes{instance=\"$nodename\"}) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "stat",
   "description": "Percentage of swap space currently used by the system",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$nodename\"} - node_memory_SwapFree_bytes{instance=\"$nodename\"}) / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\r\n  node_filesystem_size_bytes{mountpoint=\"/\", fstype=~\"ext4|xfs\", instance=\"$nodename\", job=\"$job\"}\r\n  -\r\n  node_filesystem_free_bytes{mountpoint=\"/\", fstype=~\"ext4|xfs\", instance=\"$nodename\", job=\"$job\"}\r\n)\r\n/\r\nnode_filesystem_size_bytes{mountpoint=\"/\", fstype=~\"ext4|xfs\", instance=\"$nodename\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$nodename\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$nodename\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$nodename\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$nodename\"} - node_boot_time_seconds{instance=\"$nodename\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$nodename\"}[2m])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$nodename\"} - node_memory_MemAvailable_bytes{instance=\"$nodename\"}) / node_memory_MemTotal_bytes{instance=\"$nodename\"} * 100",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(\r\n  node_filesystem_size_bytes{fstype=\"ext4\", mountpoint=\"/\", instance=\"$nodename\"}\r\n  -\r\n  node_filesystem_free_bytes{fstype=\"ext4\", mountpoint=\"/\", instance=\"$nodename\"}\r\n) / 1024 / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "sum by (instance)(\r\n  rate(node_network_receive_bytes_total{device!~\"lo|docker.*|veth.*\", instance=\"$nodename\"}[2m])\r\n) * 8 / 1000000\r\n\r\n\r\n",
     "legendFormat": "Download"
    },
    {
     "expr": "sum by (instance)(\r\n  rate(node_network_transmit_bytes_total{device!~\"lo|docker.*|veth.*\", instance=\"$nodename\"}[2m])\r\n) * 8 / 1000000",
     "legendFormat": "Upload"
    }
   ]
  }
 ]
}